language: python
python:
- '3.4'
- '3.5'
- '3.6'
- 3.7-dev
- nightly
dist: trusty
sudo: required
addons:
  postgres: '9.4'
services:
- postgresql
install: make
before_script:
- psql -c 'create database jaram_wiki;' -U postgres
- python manage.py makemigrations
script:
- python manage.py migrate
- make test
deploy:
  provider: heroku
  api_key:
    secure: AybR2KoVYSvkc9FFwzFF/bMqyfPQR1fegKb8y2EVbah0tskZGAGTqKnED8u7OtKbD8/dOHv+7TmHyFdho4ArnZj/z4TeEveB2ShW1NQbuzBWdTQZi0/JnXZ4x59D7nDW/XdeJdJNy69HKyWIJbQ5eDJ+kvoyhEZPT8K2xVF/IgQW2yaj8lbYue+NqERvRGEwiO/kZDEEpXDC/Lcw4Ap378WasHDq/XrNEyz/30YdeePvh2rKYuYoq35QyZDdPheLqRRvcdfAxDYbQgg14emDxuKtZcfqN6+v/d79PgZjludML7tuLxilJOs3vqNJj2+KxvIHDSDDb+5sOq8szM5iDpCLj1B/ufl3sjHAdbTyQZK0y7xjDmRpJsqL3NfW5IP+tQ0OKwdXQLCTNcxZlWvRUiJX4LrykmO5lOR78UfjGDyOKjn9/Tvfa7bDNDbfAcpE4zbcNDAxpODq4UXB/Dmc0b7QnFXpNy66R2y4jDkEqeGOsYaF/UwnwP+KF0yX5GWe3Fu+AJTUhp75/2jlPGMaqP5Wc+6v3/JvH1Sp8rhU5PxlP+sL2xdG37ihajF8kJQ59omZWSf8Ebupn8OdDAXK6XkdWBTR2scWMm8GZ9B9cGCpxt6ME7larGMOIWTDzHJbGtw2InZcTWa3Nbldn7T70URyFBmWJvTWtHYcEJgTA9o=
  app: jaram-wiki
  on:
    repo: Jaram2017/jaram-wiki
