language: python
python:
- '3.4'
- '3.5'
- '3.6'
- '3.7-dev'
- 'nightly'
dist: trusty
sudo: required
addons:
  postgres: '9.4'
services:
- postgresql
install: make
before_script:
- psql -c 'create database jaram_wiki;' -U postgres
- python manage.py makemigrations
script:
- python manage.py migrate
- make test
deploy:
  provider: heroku
  api_key:
    secure: HRFzY9ssGc/PVEPvpUBDkUI2zMllLFDGr2oec0flJ4tIxvsgnZtq+Vn8vD888hA6VqZUhTR8V5ty714aQSfqvlkwf2WOv0vpmh0OCCjF1zoVc5Ye5e8zckZ0nCIpIeNilZXKKR7hYFObTL0x7lKnK78sLn+s+vRTr079pKF9pXJNI6HWYkaWs7Gh+CFVDsOT4RfG/rIA4CRLV+7eSl68CGFJepeQUCl/QEUk2iBcZ5c5XVYA9+Z7QtzIHoncfG/nrMuu4S0GQOH8XaVaVtsJzqLFggOkRbRk2C8lat4UxszHjzDMF8bc7wH94UtTBUeaaA8Zuxt+aEaJYU2+eE6fWeDraHRyc0G5W3aVzCACWyvKBJIlTVhFR7aX7HLWfpyCApdb1s+mfbjudohvf3Evt+PpJxWyBp65+LHWEGkHSAKzMQ3wX0HhDUtorJg6w4tnseeYZsy2kHc1Xos6kxB+4yfM9MxkgMAPcZezjcsCrrR7PFe157zTloqoWEegJRgJU8+vKk9CXf8OgNCIx9ffIXU+fWPE4h3ksbv0bUt87OIRGsTS64WwFqSC2QsRb7luUNNXlHPLnTcCLEwzKnv0kR6Fp2VE0IqpqPd84TxzDFAIugaLfLHUiwo0+X0NTiEah6nI+2bSHh68g9wOxD7m1jzVNVPaDF65ciiXXF++dP4=
  app: jaram-wiki-test
